### ISSUE TITLE
Support for CDH 5.9.1

### ISSUE THREAD

**Issue by imochurad** [chiastic-security/phoenix-for-cloudera#10]
Is there a timeline to implement phoenix for cloudera 5.9.1? Please advise.

**Comment by apurtell** [comment]
See https://github.com/chiastic-security/phoenix-for-cloudera/tree/4.9-HBase-1.2-cdh5.9

**Comment by imochurad** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project phoenix-pherf: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/imochurad/work/ws/phoenix-for-cloudera/phoenix-pherf/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
```

I wonder if test failures is a know issue..

**Comment by apurtell** [comment]
This is a best effort project. I won't be able to fix test failures. Maybe someone else will. Patches always welcome.
