### ISSUE TITLE
Compilation Errors For Phoenix 4.6 with CDH 5.5

### ISSUE THREAD

**Issue by shahamit** [chiastic-security/phoenix-for-cloudera#4]
The current code base for 4.6-HBase-1.0-cdh5.5  branch does not compile. I tried building the jars by checking out this branch. I got a compilation error for the IndexedWALEditCodec class. I worked around it by commenting the usage of BinaryCompatibleCompressedIndexKeyValueDecoder
 & BinaryCompatibleIndexKeyValueDecoder classes.

I suppose the usage of these classes is linked with secondary indexing, is that right?
Is there a plan to fix the errors?

Thanks,
Amit.

**Comment by apurtell** [comment]
This branch was compiling - and unit tests and integration tests were passing - when I pushed it, though I suppose it is possible there were local uncommitted changes at the time or I made some other mistake. Thanks for the report. I will look at this when I have some time, probably later today.

**Comment by apurtell** [comment]
Missing PHOENIX-2477

Fixed by 2277e37
