### ISSUE TITLE
support for cdh 5.7

### ISSUE THREAD

**Issue by jesinity** [chiastic-security/phoenix-for-cloudera#6]
It would be really great to support phoenix 4.7 over CDH 5.7.0.

**Comment by busbey** [comment]
FWIW, I'm working on this now.

**Comment by apurtell** [comment]
Thanks @busbey . Please let us know where/when it's ready. Awesome

**Comment by mohanaugust** [comment]
Thanks @busbey . Looking forward for it.

**Comment by busbey** [comment]
Sorry folks, forgot this one.

The [release announcement went up on Cloudera's community site about 3 weeks ago](http://community.cloudera.com/t5/Cloudera-Labs/ANNOUNCE-Third-installment-of-Cloudera-Labs-packaging-of-Apache/m-p/42351#U42351)
