### ISSUE TITLE
Support for CDH 5.8

### ISSUE THREAD

**Issue by apurtell** [chiastic-security/phoenix-for-cloudera#7]
I pushed preliminary work (based on 4.8.0 RC2) to https://github.com/chiastic-security/phoenix-for-cloudera/tree/4.8-HBase-1.2-cdh5.8

Issues
- You have to build this with mvn ... -Dcdh.flume.version=1.6.0 because the Flume artifacts specified by the CDH parent pom for 5.8.0 are not publicly available. The available version I find with search.maven.org is 1.6.0. 
- Phoenix 4.8.0 requires Tephra 0.8.0-incubating and this version of Tephra does not have a compat module for CDH 5.2 (HBase 1.2 plus CDH specific coprocessor and client API changes). I've disabled all transactional tests, see 3b745a8cb16f771cdd54076d92a9ba126a2457e1. The remaining tests in phoenix-core pass. 
- Several issues with the phoenix-hive module. I've temporarily disabled inclusion of this module in the build. See e6a751c3977f0d46d86ec58adfeadf4f36221c20

Anyway, it's possible to build binary artifacts minus the Hive integration:

```
$ mvn clean package -DskipTests -Dcdh.flume.version=1.6.0
[...]
[INFO] Apache Phoenix ..................................... SUCCESS [  1.502 s]
[INFO] Phoenix Core ....................................... SUCCESS [ 21.716 s]
[INFO] Phoenix - Flume .................................... SUCCESS [  0.836 s]
[INFO] Phoenix - Pig ...................................... SUCCESS [  0.939 s]
[INFO] Phoenix Query Server Client ........................ SUCCESS [ 12.380 s]
[INFO] Phoenix Query Server ............................... SUCCESS [  2.211 s]
[INFO] Phoenix - Pherf .................................... SUCCESS [  2.334 s]
[INFO] Phoenix - Spark .................................... SUCCESS [ 18.906 s]
[INFO] Phoenix Client ..................................... SUCCESS [01:04 min]
[INFO] Phoenix Server ..................................... SUCCESS [  2.971 s]
[INFO] Phoenix Assembly ................................... SUCCESS [ 14.171 s]
[INFO] Phoenix - Tracing Web Application .................. SUCCESS [  1.860 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

Spark tests look good.

Highly doubtful the flume integration will work, of course.

**Comment by apurtell** [comment]
FYI @busbey @JamesRTaylor

**Comment by busbey** [comment]
Thanks for taking a look at this Andrew!

Which flume artifacts? We're supposed to publish everything, so that sounds like a bug.

For tephra, for the last labs packaging I rebuilt against CDH jars and that worked. I believe I already filed a JIRA against them for the issue, but rebuilding again should work.

**Comment by apurtell** [comment]
@busbey I saw the POM change you made for Tephra/CDH. That was for 0.7, Phoenix 4.8 needs 0.8.0-incubating. Tephra ships with a CDH compat module for HBase 1.0, not the newer stuff based on 1.2. Also, that labs version of Tephra is not publically available

As for flume, whatever is defined in the parent pom for 5.8.0 as cdh.flume.version. 0.9.4 something or other as I recall. Build failed unable to pull it from maven central or Cloudera artifactory. So I searched maven for something public, found 1.6.0, and used it.

**Comment by busbey** [comment]
Hurm. The tephra repo was supposed to get published when the Phoenix one did. I'll figure out what happened. FWIW, it was just the vanilla 1.2 compat module with the versions changed. It's source compatible for CDH, just not binary. My guess is tephra 0.8.0's 1.2 module is the same.

**Comment by apurtell** [comment]
No 1.2 compat module for tephra in maven central: http://search.maven.org/#search%7Cga%7C1%7Ctephra . They have them for 0.96, 0.98, 1.0, 1.0-cdh, and 1.1.

**Comment by JamesRTaylor** [comment]
No compat module was required for 1.2 - the 1.1 compat module is fine for
1.2

**Comment by apurtell** [comment]
Then we need a 1.1-CDH @JamesRTaylor @busbey because the 1.1 compat module is not compatible with CDH. Errors from OperationWithAttributes for one.

**Comment by JamesRTaylor** [comment]
- Poorna

Agreed, Andy.

Maybe that's what https://issues.apache.org/jira/browse/TEPHRA-176 will be?

**Comment by apurtell** [comment]
Did you mean @Poorna @JamesRTaylor  ?

**Comment by JamesRTaylor** [comment]
@poornachandra (https://github.com/poornachandra)

**Comment by busbey** [comment]
FYI, I've filed an internal ticket to get the modified tephra repo published.

For the flume-ng-core artifact, can you try wiping out the local repo and refetching? Browsing the repository, at least, things look to be present ([ref flume-ng-core:1.6.0-cdh5.8.0](https://repository.cloudera.com/artifactory/cloudera-repos/org/apache/flume/flume-ng-core/1.6.0-cdh5.8.0/)).

**Comment by busbey** [comment]
I don't think it helps with needing tephra-incubating 4.8 support, but [I got the modified tephra 0.7 published to the cloudera-labs repo](https://github.com/cloudera-labs/tephra/tree/phoenix1-0.7.1_1.3.0)

**Comment by apurtell** [comment]
> I don't think it helps with needing tephra-incubating 4.8 support, but I got the modified tephra 0.7 published to the cloudera-labs repo

Thanks Sean. You're right, but it does mean the 4.7 labs release can be reproduced publicly now, which is great.

**Comment by JamesRTaylor** [comment]
Agreed. Thanks, Sean!

**Comment by ledjon** [comment]
Did this get created/completed? I'm a little lost on where this topic ended up at.

**Comment by viswaj** [comment]
Hi @apurtell , this 4.8-HBase-1.2-cdh5.8 branch will supports for CDHv5.8 and HBasev1.2 for phoenix? Can I build and use the phoenix server/client jars in production?

**Comment by viswaj** [comment]
Please help.

**Comment by dilas** [comment]
I'm trying to build a new parcel from this branch ().

There are any command to generate a new parcel?

I just saw instructions here https://github.com/cloudera/cm_ext/wiki/Building-a-parcel and the spark-assembly module from this repo.

Any idea?

**Comment by odilontalk** [comment]
I'm trying to build a new parcel from this branch (4.8-HBase-1.2-cdh5.8).

There are any command to generate a new parcel?

I just saw instructions here https://github.com/cloudera/cm_ext/wiki/Building-a-parcel and the spark-assembly module from this repo.

Any idea?

**Comment by ls-jftheroux** [comment]
Is this stable enough for production use? I'm a bit worried about this. Especially since Cloudera seems to have abandoned their cloudera labs parcel.

**Comment by apurtell** [comment]
We have a branch for 4.9 that doesn't have these issues. Use that
